/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mux.artifactory

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A plugin
 */
class MuxArtifactoryPlugin: Plugin<Project> {

    private lateinit var extension: MuxArtifactoryPluginExtension
    private lateinit var project: Project

    override fun apply(project: Project) {
      this.project = project
      this.extension = project.extensions.create("muxArtifactory", MuxArtifactoryPluginExtension::class.java)

      // TODO: must configure artifactory after all apply()s
      // TODO:
    }
}
