/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mux.gradle.git

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A plugin that exposes some helpful functions to interact with Git for the purposes of versioning
 * and deploying libraries
 */
class GitUtilsPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    project.extensions.create("gitUtils", GitUtilsPluginExtension::class.java)
  }
}
