/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.4/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
  `java-gradle-plugin`
  id("org.jetbrains.kotlin.jvm") version "1.9.10"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  implementation(gradleApi())
  implementation("org.jfrog.buildinfo:build-info-extractor-gradle:5.1.11")
}

// todo - use the publication module for plugin version instead
version = "0.0.1"
group = "com.mux.gradle"
java {
  withSourcesJar()
}
// gradlePlugin will also create the deployments and stuff
gradlePlugin {
  val muxArtifactory by plugins.creating {
    id = "com.mux.gradle.artifactory"
    implementationClass = "mux.artifactory.MuxArtifactoryPlugin"
    displayName = "Mux Android Artifactory Plugin"
    description = "(Thinly) Automates configuring and uploading to Artifactory, allowing you to specify both dev and " +
            "release repositories"
  }
}

// Add a source set for the functional test suite
val functionalTestSourceSet = sourceSets.create("functionalTest") {
}

configurations["functionalTestImplementation"].extendsFrom(configurations["testImplementation"])
configurations["functionalTestRuntimeOnly"].extendsFrom(configurations["testRuntimeOnly"])

// Add a task to run the functional tests
val functionalTest by tasks.registering(Test::class) {
  testClassesDirs = functionalTestSourceSet.output.classesDirs
  classpath = functionalTestSourceSet.runtimeClasspath
  useJUnitPlatform()
}

gradlePlugin.testSourceSets.add(functionalTestSourceSet)

tasks.named<Task>("check") {
  // Run the functional tests as part of `check`
  dependsOn(functionalTest)
}

tasks.named<Test>("test") {
  // Use JUnit Jupiter for unit tests.
  useJUnitPlatform()
}
