/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package android.publication

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class AndroidPublicationPlugin: Plugin<Project> {

    internal lateinit var extension: AndroidPublicationPluginExtension
    internal lateinit var project: Project

    override fun apply(project: Project) {
    }
}
