/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mux.gradle.internal

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.mux.gradle.internal.greeting' plugin.
 */
class InternalDistPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.mux.gradle.internal.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
