/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mux.artifactory

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/**
 * A simple functional test for the 'mux.artifactory.greeting' plugin.
 */
class MuxArtifactoryPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }
    private val propsFile by lazy { projectDir.resolve("local.properties") }

    @Test fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('com.mux.gradle.artifactory')
            }
            
            muxArtifactory {
              contextUrl = "https://muxinc.jfrog.io/artifactory/"
              releaseRepoKey = 'default-maven-release-local'
              devRepoKey = 'default-maven-local'
              publishToProdIf { false }
            }
            
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("artifactoryPublish")
        runner.withProjectDir(projectDir)
        // NOTE!! Doesn't really pass. Can't give real values to artifactory to test, fails with 401
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'mux.artifactory.greeting'"))
    }
}
